// app/components/common/Button.vue
<template>
  <button
    :text="text"
    :class="['btn', variant === 'primary' ? 'btn-primary' : 'btn-secondary']"
    @tap="$emit('tap')"
  />
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator';

@Component
export default class Button extends Vue {
  @Prop({ default: 'primary' }) variant!: 'primary' | 'secondary';
  @Prop({ required: true }) text!: string;
}
</script>

<style lang="scss" scoped>
.btn {
  border-radius: 8;
  padding: 12 24;
  font-weight: bold;
  
  &-primary {
    background-color: var(--primary);
    color: white;
  }
  
  &-secondary {
    background-color: transparent;
    border-width: 1;
    border-color: var(--primary);
    color: var(--primary);
  }
}
</style>

// src/components/ui/Button.tsx
import React from 'react';
import { TouchableOpacity, Text, TouchableOpacityProps } from 'react-native';
import { cn } from '@/utils/cn';

interface ButtonProps extends TouchableOpacityProps {
  variant?: 'primary' | 'secondary';
  size?: 'sm' | 'md' | 'lg';
  children: React.ReactNode;
}

export function Button({
  variant = 'primary',
  size = 'md',
  children,
  className,
  ...props
}: ButtonProps) {
  return (
    <TouchableOpacity
      className={cn(
        'rounded-lg',
        variant === 'primary' ? 'bg-primary' : 'bg-white border border-primary',
        size === 'sm' ? 'px-4 py-2' : size === 'md' ? 'px-6 py-3' : 'px-8 py-4',
        className
      )}
      {...props}
    >
      <Text
        className={cn(
          'text-center font-bold',
          variant === 'primary' ? 'text-white' : 'text-primary'
        )}
      >
        {children}
      </Text>
    </TouchableOpacity>
  );
}
